name: Test VM Environment

on: [push]

jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js version
        run: node -v

      - name: Check Python version
        run: python3 --version

      - name: Check Java version
        run: java -version

      - name: Check Docker version
        run: docker --version

      - name: List all installed commands
        run: compgen -c | sort

      - name: Show environment variables
        run: env
